In [1]:

# Import the necessary libraries
from PIL import Image
from numpy import asarray
 
 
# load the image and convert into
# numpy array
img = Image.open('C:/Users/CCL/Downloads/bitwise/oip.jfif')
numpydata = asarray(img)
 
# data
print(numpydata)

[[[144 214 212]
  [144 214 212]
  [144 214 212]
  ...
  [143 213 211]
  [143 213 211]
  [143 213 211]]

 [[112 182 180]
  [111 183 180]
  [112 182 180]
  ...
  [108 180 177]
  [109 179 177]
  [108 180 177]]

 [[114 186 183]
  [112 187 183]
  [114 186 183]
  ...
  [110 185 181]
  [112 184 181]
  [110 185 181]]

 ...

 [[ 97 153 154]
  [ 95 153 154]
  [ 97 153 154]
  ...
  [ 95 153 154]
  [ 97 153 154]
  [ 95 153 154]]

 [[ 94 144 145]
  [ 93 144 145]
  [ 94 144 145]
  ...
  [ 93 144 145]
  [ 94 144 145]
  [ 93 144 145]]

 [[205 253 255]
  [205 253 255]
  [205 253 255]
  ...
  [205 253 255]
  [205 253 255]
  [205 253 255]]]
